# Site settings
title: Blog of Kai Yi
email: williamyi96@gmail.com
description: "Creating a Learning Machine"
baseurl: ""
url: "https://kaiyi.me"
blogurl: "williamyi96.github.io/blog"
#twitter_username: karpathy
github_username:  williamyi96

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
